/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poggioadventure.ui;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author valen
 */
public class UI_InitGame extends javax.swing.JFrame {

    /**
     * Creates new form UI_InitGame
     */
    public UI_InitGame() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/scudoPoggio.png"));
        JLabel label = new JLabel(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        myButton1 = new com.mycompany.poggioadventure.ui.MyButton();
        myButton2 = new com.mycompany.poggioadventure.ui.MyButton();
        myButton3 = new com.mycompany.poggioadventure.ui.MyButton();
        myButton4 = new com.mycompany.poggioadventure.ui.MyButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Crimson Pro", 2, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PoggioAdventure");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 60));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 60));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 500, 85));

        myButton1.setText("NUOVA PARTITA");
        myButton1.setToolTipText("");
        myButton1.setBorderColor(new java.awt.Color(51, 0, 255));
        myButton1.setColor(new java.awt.Color(255, 0, 0));
        myButton1.setColorClick(new java.awt.Color(51, 0, 255));
        myButton1.setColorOver(new java.awt.Color(255, 0, 0));
        myButton1.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        myButton1.setMaximumSize(new java.awt.Dimension(200, 55));
        myButton1.setMinimumSize(new java.awt.Dimension(200, 55));
        myButton1.setPreferredSize(new java.awt.Dimension(200, 55));
        myButton1.setRadius(25);
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 166, -1, -1));

        myButton2.setText("CARICA PARTITA");
        myButton2.setBorderColor(new java.awt.Color(51, 0, 255));
        myButton2.setColor(new java.awt.Color(255, 0, 0));
        myButton2.setColorClick(new java.awt.Color(51, 0, 255));
        myButton2.setColorOver(new java.awt.Color(255, 0, 0));
        myButton2.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        myButton2.setMaximumSize(new java.awt.Dimension(200, 55));
        myButton2.setMinimumSize(new java.awt.Dimension(200, 55));
        myButton2.setPreferredSize(new java.awt.Dimension(200, 55));
        myButton2.setRadius(25);
        getContentPane().add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 275, -1, -1));

        myButton3.setText("CLASSIFICA");
        myButton3.setBorderColor(new java.awt.Color(51, 0, 255));
        myButton3.setColor(new java.awt.Color(255, 0, 0));
        myButton3.setColorClick(new java.awt.Color(51, 0, 255));
        myButton3.setColorOver(new java.awt.Color(255, 0, 0));
        myButton3.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        myButton3.setMaximumSize(new java.awt.Dimension(200, 55));
        myButton3.setMinimumSize(new java.awt.Dimension(200, 55));
        myButton3.setPreferredSize(new java.awt.Dimension(200, 55));
        myButton3.setRadius(25);
        getContentPane().add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 384, -1, -1));

        myButton4.setText("ESCI");
        myButton4.setBorderColor(new java.awt.Color(51, 0, 255));
        myButton4.setColor(new java.awt.Color(255, 0, 0));
        myButton4.setColorClick(new java.awt.Color(51, 0, 255));
        myButton4.setColorOver(new java.awt.Color(255, 0, 0));
        myButton4.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        myButton4.setRadius(25);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 100, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scudoPoggio.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 28, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scudoPoggio.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 28, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PoggioBack.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1000, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_InitGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.mycompany.poggioadventure.ui.MyButton myButton1;
    private com.mycompany.poggioadventure.ui.MyButton myButton2;
    private com.mycompany.poggioadventure.ui.MyButton myButton3;
    private com.mycompany.poggioadventure.ui.MyButton myButton4;
    // End of variables declaration//GEN-END:variables
}
