/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poggioadventure.ui;

import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author valen
 */
public class UI_InitGame extends javax.swing.JFrame {

    /**
     * Creates new form UI_InitGame
     */
    public UI_InitGame() {
        initComponents();
        this.setLocationRelativeTo(null); //Inizializza il Jframe al centro dello schermo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newGame = new com.mycompany.poggioadventure.ui.MyButton();
        loadGame = new com.mycompany.poggioadventure.ui.MyButton();
        rankingBottom = new com.mycompany.poggioadventure.ui.MyButton();
        exit = new com.mycompany.poggioadventure.ui.MyButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Crimson Pro", 2, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PoggioAdventure");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 60));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 60));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 500, 85));

        newGame.setText("NUOVA PARTITA");
        newGame.setToolTipText("");
        newGame.setActionCommand("newGame");
        newGame.setBorderColor(new java.awt.Color(51, 0, 255));
        newGame.setColor(new java.awt.Color(255, 0, 0));
        newGame.setColorClick(new java.awt.Color(51, 0, 255));
        newGame.setColorOver(new java.awt.Color(255, 0, 0));
        newGame.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        newGame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newGame.setMaximumSize(new java.awt.Dimension(200, 55));
        newGame.setMinimumSize(new java.awt.Dimension(200, 55));
        newGame.setPreferredSize(new java.awt.Dimension(200, 55));
        newGame.setRadius(25);
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });
        getContentPane().add(newGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 166, -1, -1));

        loadGame.setText("CARICA PARTITA");
        loadGame.setBorderColor(new java.awt.Color(51, 0, 255));
        loadGame.setColor(new java.awt.Color(255, 0, 0));
        loadGame.setColorClick(new java.awt.Color(51, 0, 255));
        loadGame.setColorOver(new java.awt.Color(255, 0, 0));
        loadGame.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        loadGame.setMaximumSize(new java.awt.Dimension(200, 55));
        loadGame.setMinimumSize(new java.awt.Dimension(200, 55));
        loadGame.setPreferredSize(new java.awt.Dimension(200, 55));
        loadGame.setRadius(25);
        getContentPane().add(loadGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 275, -1, -1));

        rankingBottom.setText("CLASSIFICA");
        rankingBottom.setBorderColor(new java.awt.Color(51, 0, 255));
        rankingBottom.setColor(new java.awt.Color(255, 0, 0));
        rankingBottom.setColorClick(new java.awt.Color(51, 0, 255));
        rankingBottom.setColorOver(new java.awt.Color(255, 0, 0));
        rankingBottom.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        rankingBottom.setMaximumSize(new java.awt.Dimension(200, 55));
        rankingBottom.setMinimumSize(new java.awt.Dimension(200, 55));
        rankingBottom.setPreferredSize(new java.awt.Dimension(200, 55));
        rankingBottom.setRadius(25);
        rankingBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingBottomActionPerformed(evt);
            }
        });
        getContentPane().add(rankingBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 384, -1, -1));

        exit.setText("ESCI");
        exit.setBorderColor(new java.awt.Color(51, 0, 255));
        exit.setColor(new java.awt.Color(255, 0, 0));
        exit.setColorClick(new java.awt.Color(51, 0, 255));
        exit.setColorOver(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Crimson Pro", 2, 24)); // NOI18N
        exit.setRadius(25);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 100, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scudoPoggio.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 28, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scudoPoggio.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 28, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PoggioBack.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1000, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    //Questo metodo viene invoca la creazione del Jframe utile a visualizzare la classifica
    private void rankingBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingBottomActionPerformed
        UI_Ranking rankFrame = new UI_Ranking();
        
        // Ottieni la posizione del JFrame padre (quello che contiene il JButton)
        Point parentLocation = this.getLocation();

        // Imposta la posizione del nuovo JFrame per essere uguale a quella del JFrame padre
        rankFrame.setLocation(parentLocation);
        
        rankFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Se chiudo il nuovo Jframe creato non viene chiuso anche il Jframe padre
        
        rankFrame.setVisible(true);
    }//GEN-LAST:event_rankingBottomActionPerformed

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
        UI_LoadGame loadGameFrame = new UI_LoadGame();
        // Ottieni la posizione del JFrame padre (quello che contiene il JButton)
        Point parentLocation = this.getLocation();

        // Imposta la posizione del nuovo JFrame per essere uguale a quella del JFrame padre
        loadGameFrame.setLocation(parentLocation);
        
        loadGameFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Se chiudo il nuovo Jframe creato non viene chiuso anche il Jframe padre
        
        loadGameFrame.setVisible(true);
    }//GEN-LAST:event_newGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_InitGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_InitGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.poggioadventure.ui.MyButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.mycompany.poggioadventure.ui.MyButton loadGame;
    private com.mycompany.poggioadventure.ui.MyButton newGame;
    private com.mycompany.poggioadventure.ui.MyButton rankingBottom;
    // End of variables declaration//GEN-END:variables
}
